---
# Default variables (can be overridden)
workspace: "/home/vagrant/deploy_app_harbor"
IMAGE: "deependrabhatta/java_app:V_{{ build_number }}"
compose_file: "compose.yaml"
env_file: ".env"
sql: "init.sql"
src_path: "/home/vagrant/java_app_required_files"