---
- name: Delete all contents of deploy_app_harbor directory
  ansible.builtin.shell: "rm -rf {{ workspace }}/*"
  become: yes

- name: Copy Docker compose file
  ansible.builtin.copy:
    src: "{{ src_path }}/docker-compose.yml"
    dest: "{{ workspace }}/{{ compose_file }}"

# - name: Copy wait-for-it.sh
#   ansible.builtin.copy:
#     src: "/home/vagrant/java/wait-for-it.sh"
#     dest: "{{ workspace }}/{{ wait }}"

- name: Copy init.sql
  ansible.builtin.copy:
    src: "{{ src_path }}/init.sql"
    dest: "{{ workspace }}/{{ sql }}"


- name: Create environment file
  ansible.builtin.template:
    src: ".env.j2"
    dest: "{{ workspace }}/{{ env_file }}"