# roles/app_deployer/tasks/04_cleanup.yml
---

- name: Compute tags to remove
  set_fact:
    # Make a list of all build numbers less than the current one
    old_builds: "{{ range(1, (build_number|int - 1) + 1) | map('string') | list }}"

- name: Remove old versioned images
  community.docker.docker_image:
    name: "harbor.registry.local/java_app/taskmanager:V_{{ item }}"
    state: absent
  loop: "{{ old_builds }}"
  loop_control:
    label: "V_{{ item }}"
  ignore_errors: yes